[[fonts]]
name = "kirsch"
xs = [2, 3]
zip_includes = ["README.md", "LICENSE", "AUTHORS"]
x_format = "{name}_{x}x"
sfnt_lang = "English (US)"
ttfix = '''
f.os2_version = 4
f.os2_vendor = "BenP"
f.os2_panose = (2, 0, 6, 9, 0, 0, 0, 0, 0, 0)
f.os2_weight_width_slope_only = True
f.em = 1600
for g in f.glyphs():
    g.width = 600
'''

[[fonts.sfnt]]
"UniqueID" = "molarmanful: kirsch: 2024"
"Vendor URL" = "https://github.com/molarmanful/kirsch"
"Designer" = "Benjamin Pang"
"Designer URL" = "https://benpa.ng"
"License" = "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"
"License URL" = "https://scripts.sil.org/OFL"
