[[fonts]]
name = "kirsch"
xs = [2, 3]
ttfix = '''
f.os2_version = 4
f.os2_vendor = "BenP"
f.os2_panose = (0, 0, 0, 9, 0, 0, 0, 0, 0, 0)
f.os2_weight_width_slope_only = True
'''

[fonts.sfnt]
"UniqueID" = "molarmanful: kirsch: 2024"
"Vendor URL" = "https://github.com/molarmanful/kirsch"
"Designer" = "Benjamin Pang"
"Designer URL" = "https://benpa.ng"
"License" = "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"
"License URL" = "https://scripts.sil.org/OFL"
