[[fonts]]
name = "kirsch"
font_size = 16

[fonts.clrs]
bg = "#140011"
fg = "#e6cfd6"
base = [
  "#330a1f",
  "#ff738a",
  "#73e673",
  "#ff9966",
  "#8cc6ff",
  "#c291f2",
  "#73e6e6",
  "#668080",
  "#4d1339",
  "#ff738a",
  "#73e673",
  "#f2de79",
  "#8cc6ff",
  "#c291f2",
  "#73e6e6",
  "#b8e6de",
]

[[fonts.gens]]
name = "sample"
txts = [
  "prog",
  "eng",
  "multi",
  "scala",
  "clojure",
  "go",
  "svelte",
  "apl",
  "bqn",
  "uiua",
  "engalt",
  "pretty",
  "math",
  "box",
  "braille",
  "nerd",
]

[[fonts.gens]]
name = "all"
txts = ["header", "sample"]
