---
plugins: [prettier-plugin-svelte]
trailingComma: es5
tabWidth: 2
semi: false
singleQuote: true
arrowParens: avoid
svelteSelfCloseElements: always
svelteSelfCloseComponents: always
experimentalTernaries: true
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
